<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
<TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>BH.UI.Excel</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <OutputPath>..\Build\</OutputPath>
    <FallbackCulture>en-US</FallbackCulture>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(TargetPath)&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;xcopy &quot;$(TargetDir)*.xll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;xcopy &quot;$(TargetDir)*.dna&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;xcopy &quot;$(TargetDir)ExcelDna.IntelliSense.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;call &quot;$(DevEnvDir)..\..\VC\Auxiliary\Build\vcvarsall.bat&quot; x86&#xD;&#xA;call &quot;$(DevEnvDir)..\Tools\VsDevCmd.bat&quot;&#xD;&#xA;xcopy &quot;$(NuGetPackageRoot)exceldna.integration\1.9.0\lib\net462\ExcelDna.Integration.dll&quot; &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;tlbexp.exe &quot;$(ProgramData)\BHoM\Assemblies\$(TargetName)$(TargetExt)&quot; /out:&quot;$(ProgramData)\BHoM\Assemblies\$(TargetName).tlb&quot;&#xD;&#xA;del &quot;$(ProgramData)\BHoM\Assemblies\ExcelDna.Integration.dll&quot;" />
  </Target>
  <ItemGroup>
    <Reference Include="Adapter_Engine">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Adapter_Engine.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Adapter_oM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Adapter_oM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="BHoM">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(ProgramData)\BHoM\Assemblies\BHoM.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BHoM_Adapter">
      <HintPath>$(ProgramData)\BHoM\Assemblies\BHoM_Adapter.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="BHoM_Engine">
      <HintPath>$(ProgramData)\BHoM\Assemblies\BHoM_Engine.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="BHoM_UI">
      <HintPath>$(ProgramData)\BHoM\Assemblies\BHoM_UI.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Data_oM">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(ProgramData)\BHoM\Assemblies\Data_oM.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Reflection_Engine">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(ProgramData)\BHoM\Assemblies\Reflection_Engine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Serialiser_Engine">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(ProgramData)\BHoM\Assemblies\Serialiser_Engine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UI_Engine">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(ProgramData)\BHoM\Assemblies\UI_Engine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UI_oM">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(ProgramData)\BHoM\Assemblies\UI_oM.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Versioning_oM">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(ProgramData)\BHoM\Assemblies\Versioning_oM.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="office">
      <HintPath>..\libs\office.dll</HintPath>
      <EmbedInteropTypes>False</EmbedInteropTypes>
    </Reference>
    <PackageReference Include="ExcelDna.AddIn" Version="1.9.0" />
    <PackageReference Include="System.Resources.Extensions" Version="9.0.0" />
    <PackageReference Include="ExcelDna.Integration" Version="1.9.0" />
    <PackageReference Include="ExcelDna.IntelliSense" Version="1.1.0" />
    <PackageReference Include="ExcelDna.Registration" Version="1.9.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Office.Interop.Excel" Version="15.0.4795.1000" EmbedInteropTypes="true" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ExcelUI_Engine\ExcelUI_Engine.csproj" />
  </ItemGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <StartArguments>
    </StartArguments>
    <StartAction>Program</StartAction>
    <StartProgram>C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE</StartProgram>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <StartProgram>C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE</StartProgram>
    <StartArguments>
    </StartArguments>
    <StartAction>Program</StartAction>
  </PropertyGroup>
</Project>
